using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AweEditor
{
    /// <summary>
    /// BlockType corresponds to Minecraft Bock IDs for ease of import
    /// (see http://www.minecraftwiki.net/wiki/Data_values#Block_IDs)
    /// </summary>
    public enum BlockType
    {
        Air,
        Stone,
        Grass,
        Dirt,
        Cobblestone,
        WoodenPlanks,
        Saplings,
        Bedrock,
        Water,
        StationaryWater,
        Lava,
        StationaryLava,
        Sand,
        Gravel,
        GoldOre,
        IronOre,
        CoalOre,
        Wood,
        Leaves,
        Sponge,
        Glass,
        LapisLazuliOre,
        LapisLazuliBlock,
        Dispenser,
        Sandstone,
        NoteBlock,
        Bed,
        PoweredRail,
        DetectorRail,
        StickyPiston,
        Cobweb,
        TallGrass,
        DeadBush,
        Piston,
        PistonExtension,
        Wool,
        BlockMovedByPiston,
        Dandelion,
        Rose,
        BrownMushroom,
        RedMushroom,
        BlockofGold,
        BlockofIron,
        DoubleSlabs,
        Slabs,
        Bricks,
        TNT,
        Bookshelf,
        MossStone,
        Obsidian,
        Torch,
        Fire,
        MonsterSpawner,
        OakWoodStairs,
        Chest,
        RedstoneWire,
        DiamondOre,
        BlockofDiamond,
        CraftingTable,
        WheatSeeds,
        Farmland,
        Furnace,
        BurningFurance,
        SignPost,
        WoodenDoor,
        Ladders,
        Rails,
        CobblestoneStairs,
        WallSign,
        Lever,
        StonePressurePlate,
        IronDoor,
        WoodenPressurePlate,
        ReadstoneOre,
        GlowingRedstoneOre,
        RedstoneTorchI,
        ReadstoneTorchA,
        StoneButton,
        Snow,
        Ice,
        SnowBlock,
        Cactus,
        ClayBlock,
        SugarCane,
        Jukebox,
        Fence,
        Pumpkin,
        Netherrack,
        SoulSand,
        GlowstoneBlock,
        NetherPortal,
        JackoLantern,
        CakeBlock,
        RedstoneRepeaterI,
        ReadstoneRepeaterA,
        LockedChest,
        Trapdoor,
        MonsterEgg,
        StoneBricks,
        HugeBrownMushroom,
        HugeRedMushroom,
        IronBars,
        GlassPane,
        Melon,
        PumpkinStem,
        MelonStem,
        Vines,
        FenceGate,
        BrickStairs,
        StoneBrickStairs,
        Mycelium,
        LilyPad,
        NetherBrick,
        NetherBrickFence,
        NetherBrickStairs,
        NetherWart,
        EnchantmentTable,
        BrewingStand,
        Cauldron,
        EndPortal,
        EndPortalFrame,
        EndStone,
        DragonEgg,
        RedstoneLampI,
        ReadstoneLampA,
        WoodenDoubleSlab,
        WoodenSlab,
        CocoaPod,
        SandstoneStairs,
        EmeraldOre,
        EnderChest,
        TripwireHook,
        Tripwire,
        BlockofEmerald,
        SpruceWoodStairs,
        BirchWoodStairs,
        JungleWoodStairs,
        CommandBlock,
        Beacon,
        CobblestoneWall,
        FlowerPot,
        Carrots,
        Potatoes,
        WoodenButton,
        MobHeads,
        Anvil,
        TrappedChest,
        WeightedPressurePlateL,
        WeightedPressurePlateH,
        ReadstoneComparatorI,
        ReadstoneComparatorA,
        DaylightSensor,
        BlockofRedstone,
        NetherQuartzOre,
        Hopper,
        BlockofQuartz,
        QuartzStairs,
        ActivatorRail,
        Dropper,
    }

    /// <summary>
    /// A class to represent voxel terrain
    /// </summary>
    public class VoxelTerrain
    {
        List<SubChunk> sc;
        int xPos;
        int zPos;

        public VoxelTerrain(List<SubChunk> i, int xP, int zP)
        {
            sc = i;
            xPos = xP;
            zPos = zP;
        }
    }
}
